# Generated by Django 4.0 on 2022-01-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_online_alter_dreamreal_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dreamreal',
            table='dreamreal',
        ),
        migrations.AlterModelTable(
            name='online',
            table='online',
        ),
    ]
